server:
   port: 10040

spring:
   application:
      name: @pom.artifactId@
   cloud:
      nacos:
         discovery:
            server-addr: 127.0.0.1:8848
         config:
            server-addr: 127.0.0.1:8848
      sentinel:
         transport:
            port: 8719
            dashboard: localhost:8084

feign.sentinel.enabled: true
