server:
   port: 10097

spring:
   application:
      name: @pom.artifactId@
   cloud:
      nacos:
         discovery:
            server-addr: 127.0.0.1:8848
         config:
            server-addr: 127.0.0.1:8848
      sentinel:
         transport:
            port: 8719
            dashboard: localhost:8084
dubbo:
   registry:
      address: spring-cloud://127.0.0.1
   cloud:
      subscribed-services: spring-cloud-dubbo
   application:
      qos:
         enable: false

feign.sentinel.enabled: true
