server:
   port: 10098

spring:
   application:
      name: @pom.artifactId@
   cloud:
      stream:
         rocketmq:
            binder:
               name-server: 127.0.0.1:9876
         bindings:
            output:
               destination: test-topic
               content-type: application/json
            input:
               destination: test-topic
               content-type: application/json
               group: test-group
      nacos:
         discovery:
            server-addr: 127.0.0.1:8848
      sentinel:
         transport:
            port: 8719
            dashboard: localhost:8084

management.endpoint.health.show-details: always

#feign.sentinel.enabled: true
#
#app:
#   id: @pom.artifactId@
#
#apollo:
#   meta: http://localhost:8080